apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: headlamp
  namespace: headlamp
spec:
  hosts: ["headlamp.${DOMAIN}"]
  gateways: ["istio-system/public"]
  http:
    - route:
        - destination: { host: headlamp.headlamp.svc.cluster.local, port: { number: 80 } }
